spring:
  application:
    name: APIGATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "/**"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: crops-service
          uri: lb://CROPS-SERVICE
          predicates:
            - Path=/crops/**
    
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
     
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            
        
              



server:
  port: 9900

management:
  endpoint:
    gateway:
      enabled: true



